spring:
  application:
    name: kickspot
  datasource:
    url: jdbc:postgresql://localhost:5432/kickspot
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    

