spring:
  application:
    name: kickspot
  datasource:
    url: jdbc:postgresql://localhost:5432/kickspot
    username: postgres
    password: 123456
    hikari: 
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true


# smtp configuration

  mail:
    host: smtp.gmail.com
    port: 587
    username: bikalrai2785@gmail.com
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true