spring:
  application:
    name: kickspot
  datasource:
    url: jdbc:postgresql://localhost:5432/kickspot
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

secret:
  key: 9084b7906766700f8ef9384881b51c9c59e3ed0d4920582c16cfcbe20ded9161
    

